<a href="https://colab.research.google.com/github/jyothi1235/convolutionNeuralNetwork/blob/main/MNIST_New.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import torch
from torchvision import datasets, transforms

In [26]:
dataset = datasets.MNIST(root='./data', train=True, download=True,
                         transform=transforms.ToTensor())

In [27]:
x_train = dataset.data
y_train = dataset.targets

In [28]:
selected_classes = [0, 1, 2]

In [29]:
for cls in selected_classes:
    indices = (y_train == cls).nonzero(as_tuple=True)[0][:100]
    print(indices)

tensor([   1,   21,   34,   37,   51,   56,   63,   68,   69,   75,   81,   88,
          95,  108,  114,  118,  119,  121,  156,  169,  192,  206,  209,  210,
         216,  229,  232,  234,  246,  249,  260,  283,  293,  296,  303,  320,
         326,  359,  399,  427,  429,  435,  440,  451,  453,  458,  462,  464,
         473,  489,  519,  524,  526,  527,  542,  577,  582,  596,  603,  612,
         633,  639,  656,  662,  666,  667,  668,  669,  689,  702,  709,  712,
         733,  743,  745,  776,  781,  787,  790,  818,  825,  849,  859,  860,
         869,  872,  889,  903,  927,  943,  949,  952,  957,  965,  979,  984,
         997, 1000, 1015, 1018])
tensor([  3,   6,   8,  14,  23,  24,  40,  59,  67,  70,  72,  77,  78,  99,
        102, 104, 105, 112, 113, 124, 128, 134, 152, 174, 177, 184, 200, 201,
        205, 208, 211, 224, 231, 248, 251, 269, 270, 276, 290, 309, 310, 315,
        345, 351, 355, 357, 358, 366, 382, 394, 397, 398, 406, 408, 416, 443,
        447, 45

In [30]:
x_final, y_final = [], []
for cls in selected_classes:
    indices = (y_train == cls).nonzero(as_tuple=True)[0][:100]
    x_final.append(x_train[indices])
    y_final.append(y_train[indices])

In [31]:
len(x_final)

3

In [32]:
xx = torch.cat(x_final)
yy = torch.cat(y_final)

In [33]:
yy

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [34]:
from torch.utils.data import TensorDataset, DataLoader

In [35]:
dataset = TensorDataset(xx, yy)

In [36]:
data = DataLoader(dataset, batch_size=32, shuffle=True)

In [38]:
# xx was [300, 28, 28]
# unsqueeze(1) makes it [300, 1, 28, 28]
xx_reshaped = xx.unsqueeze(1).float()

# Now create the dataset with the reshaped tensor
dataset = TensorDataset(xx_reshaped, yy)
data = DataLoader(dataset, batch_size=32, shuffle=True)

# Test it
for batch in data:
    print(batch[0].shape) # Output: torch.Size([32, 1, 28, 28])
    break

torch.Size([32, 1, 28, 28])


In [40]:
for batch in data:
    images, labels = batch

    print("Input shape:", images.shape)

    output = mod(images)   # PASS INTO MODEL

    print("Output shape:", output.shape)

    break

Input shape: torch.Size([32, 1, 28, 28])
Output shape: torch.Size([32, 3])


In [41]:
import torch
import torch.nn as nn
from torch.optim import Adam

class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        # 1 input channel (grayscale), 32 filters, 3x3 kernel
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
        self.maxm = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.relu = nn.ReLU()
        self.flatten = nn.Flatten()

        # After 2 MaxPools: 28 -> 14 -> 7. So flattened size is 64 * 7 * 7
        self.linear1 = nn.Linear(64 * 7 * 7, 128)
        self.linear2 = nn.Linear(128, 3)

    def forward(self, x):
        # x starts as (batch, 1, 28, 28)
        x = self.relu(self.conv1(x)) # (batch, 32, 28, 28)
        x = self.maxm(x)             # (batch, 32, 14, 14)
        x = self.relu(self.conv2(x)) # (batch, 64, 14, 14)
        x = self.maxm(x)             # (batch, 64, 7, 7)
        x = self.flatten(x)          # (batch, 3136)
        x = self.relu(self.linear1(x))
        x = self.linear2(x)          # (batch, 3)
        return x

mod = MyNet()

In [42]:
# 1. Prepare Data (Add the channel dimension)
# xx: [300, 28, 28] -> [300, 1, 28, 28]
X = xx.unsqueeze(1).float() / 255.0
Y = yy.long()

# 2. Setup Training Tools
loss_fn = nn.CrossEntropyLoss()
optimizer = Adam(mod.parameters(), lr=0.001)

# 3. Training Loop
for epoch in range(101):
   # Output: torch.Size([32, 1, 28, 28]

    optimizer.zero_grad()           # Clear old gradients
    yp = mod(X)                     # Forward pass
    ls = loss_fn(yp, Y)             # Calculate loss
    ls.backward()                   # Backpropagation
    optimizer.step()                # Update weights

    if epoch % 10 == 0:
        # Calculate accuracy for display
        _, predicted = torch.max(yp, 1)
        acc = (predicted == Y).sum().item() / Y.size(0)
        print(f"Epoch {epoch} | Loss: {ls.item():.4f} | Acc: {acc*100:.1f}%")

Epoch 0 | Loss: 1.1024 | Acc: 33.3%
Epoch 10 | Loss: 0.1641 | Acc: 95.3%
Epoch 20 | Loss: 0.0646 | Acc: 97.3%
Epoch 30 | Loss: 0.0143 | Acc: 99.7%
Epoch 40 | Loss: 0.0038 | Acc: 100.0%
Epoch 50 | Loss: 0.0015 | Acc: 100.0%
Epoch 60 | Loss: 0.0007 | Acc: 100.0%
Epoch 70 | Loss: 0.0005 | Acc: 100.0%
Epoch 80 | Loss: 0.0004 | Acc: 100.0%
Epoch 90 | Loss: 0.0003 | Acc: 100.0%
Epoch 100 | Loss: 0.0003 | Acc: 100.0%
